# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MFMod models in Python with ModelFlow
author: Ib Hansen
#logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  # execute_notebooks: cache
  timeout: 200

  
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  colab_url: "https://colab.research.google.com"

repository:
  url                       : "https://github.com/IbHansen/modelflow manual"   # Online location of the book
  path_to_book              : working_paper/thebook  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: False
  use_repository_button: True
parse:
  myst_enable_extensions:
   # don't forget to list any other extensions you want enabled,
   # including those that are enabled by default!
   - amsmath
   - dollarmath
   - colon_fence
  
